boot.o: boot.S multiboot.h x86_desc.h types.h
idt_linkage.o: idt_linkage.S idt_linkage.h
x86_desc.o: x86_desc.S x86_desc.h types.h
filesystem.o: filesystem.c filesystem.h types.h lib.h terminal.h \
  keyboard.h i8259.h speaker.h pit.h rtc.h scheduler.h system_call.h \
  x86_desc.h page.h vga_modex.h data/graphic.h data/../types.h \
  data/music.h data/terminal_icon.h data/desktop.h
i8259.o: i8259.c i8259.h types.h lib.h terminal.h keyboard.h speaker.h \
  pit.h rtc.h scheduler.h system_call.h filesystem.h x86_desc.h page.h \
  vga_modex.h data/graphic.h data/../types.h data/music.h \
  data/terminal_icon.h data/desktop.h
idt.o: idt.c idt.h lib.h types.h terminal.h keyboard.h i8259.h speaker.h \
  pit.h rtc.h scheduler.h system_call.h filesystem.h x86_desc.h page.h \
  vga_modex.h data/graphic.h data/../types.h data/music.h \
  data/terminal_icon.h data/desktop.h idt_linkage.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h terminal.h \
  keyboard.h i8259.h speaker.h pit.h rtc.h scheduler.h system_call.h \
  filesystem.h page.h vga_modex.h data/graphic.h data/../types.h \
  data/music.h data/terminal_icon.h data/desktop.h debug.h tests.h idt.h \
  mouse.h data/mouse_graph.h
keyboard.o: keyboard.c keyboard.h types.h lib.h terminal.h scheduler.h \
  system_call.h filesystem.h x86_desc.h page.h vga_modex.h data/graphic.h \
  data/../types.h data/music.h data/terminal_icon.h data/desktop.h rtc.h \
  i8259.h pit.h speaker.h signal.h
lib.o: lib.c lib.h types.h terminal.h keyboard.h i8259.h speaker.h pit.h \
  rtc.h scheduler.h system_call.h filesystem.h x86_desc.h page.h \
  vga_modex.h data/graphic.h data/../types.h data/music.h \
  data/terminal_icon.h data/desktop.h
mouse.o: mouse.c mouse.h types.h lib.h terminal.h keyboard.h i8259.h \
  speaker.h pit.h rtc.h scheduler.h system_call.h filesystem.h x86_desc.h \
  page.h vga_modex.h data/graphic.h data/../types.h data/music.h \
  data/terminal_icon.h data/desktop.h data/mouse_graph.h
page.o: page.c page.h types.h lib.h terminal.h keyboard.h i8259.h \
  speaker.h pit.h rtc.h scheduler.h system_call.h filesystem.h x86_desc.h \
  vga_modex.h data/graphic.h data/../types.h data/music.h \
  data/terminal_icon.h data/desktop.h
pit.o: pit.c pit.h lib.h types.h terminal.h keyboard.h i8259.h speaker.h \
  rtc.h scheduler.h system_call.h filesystem.h x86_desc.h page.h \
  vga_modex.h data/graphic.h data/../types.h data/music.h \
  data/terminal_icon.h data/desktop.h
rtc.o: rtc.c rtc.h i8259.h types.h lib.h terminal.h keyboard.h speaker.h \
  pit.h scheduler.h system_call.h filesystem.h x86_desc.h page.h \
  vga_modex.h data/graphic.h data/../types.h data/music.h \
  data/terminal_icon.h data/desktop.h
scheduler.o: scheduler.c scheduler.h system_call.h filesystem.h types.h \
  lib.h terminal.h keyboard.h i8259.h speaker.h pit.h rtc.h x86_desc.h \
  page.h vga_modex.h data/graphic.h data/../types.h data/music.h \
  data/terminal_icon.h data/desktop.h
signal.o: signal.c signal.h types.h lib.h terminal.h keyboard.h i8259.h \
  speaker.h pit.h rtc.h scheduler.h system_call.h filesystem.h x86_desc.h \
  page.h vga_modex.h data/graphic.h data/../types.h data/music.h \
  data/terminal_icon.h data/desktop.h
speaker.o: speaker.c speaker.h types.h lib.h terminal.h keyboard.h \
  i8259.h scheduler.h system_call.h filesystem.h x86_desc.h page.h \
  vga_modex.h data/graphic.h data/../types.h data/music.h \
  data/terminal_icon.h data/desktop.h rtc.h pit.h
system_call.o: system_call.c system_call.h filesystem.h types.h lib.h \
  terminal.h keyboard.h i8259.h speaker.h pit.h rtc.h scheduler.h page.h \
  x86_desc.h vga_modex.h data/graphic.h data/../types.h data/music.h \
  data/terminal_icon.h data/desktop.h
terminal.o: terminal.c terminal.h lib.h types.h keyboard.h i8259.h \
  speaker.h pit.h rtc.h scheduler.h system_call.h filesystem.h x86_desc.h \
  page.h vga_modex.h data/graphic.h data/../types.h data/music.h \
  data/terminal_icon.h data/desktop.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h terminal.h keyboard.h \
  i8259.h speaker.h pit.h rtc.h scheduler.h system_call.h filesystem.h \
  page.h vga_modex.h data/graphic.h data/../types.h data/music.h \
  data/terminal_icon.h data/desktop.h
vga_modex.o: vga_modex.c vga_modex.h lib.h types.h terminal.h keyboard.h \
  i8259.h speaker.h pit.h rtc.h scheduler.h system_call.h filesystem.h \
  x86_desc.h page.h data/graphic.h data/../types.h data/music.h \
  data/terminal_icon.h data/desktop.h
desktop.o: data/desktop.c data/desktop.h data/../types.h
graphic.o: data/graphic.c data/graphic.h data/../types.h
mouse_graph.o: data/mouse_graph.c data/mouse_graph.h data/../types.h
music.o: data/music.c data/music.h data/../types.h
terminal_icon.o: data/terminal_icon.c data/terminal_icon.h \
  data/../types.h
